#!/usr/bin/env bash

set -uxo pipefail

# bluetoothctl >= 5.65: bluetoothctl devices Paired
# bluetoothctl <  5.65: bluetoothctl paired-devices
for dev in $(bluetoothctl devices Paired | cut -d\  -f2); do
  bluetoothctl connect "$dev"
done
