#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# Port of HTTP(S) proxy server on the local end
port: 8080
# Port of SOCKS5 proxy server on the local end
socks-port: 1080
# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7890

# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: debug

proxy-providers:
  proxies:
    type: file
    path: ./proxies.yaml

proxy-groups:
- name: proxy
  type: select
  use:
  - proxies

rule-providers:
  direct:
    behavior: classical
    type: file
    path: ./direct.yaml
  private:
    behavior: classical
    type: file
    path: ./private.yaml

rules:
  - RULE-SET,direct,DIRECT
  - RULE-SET,private,proxy
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,proxy
